name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up FTP credentials
      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        echo "FTP Username: $FTP_USERNAME"
        echo "FTP Password: $FTP_PASSWORD"

    - name: Deploy to FTP server
      run: |
        ftp-deploy --username $FTP_USERNAME --password $FTP_PASSWORD --server ftp.dhirajghimire.com.np
