name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Install FTP deployment tool
      run: npm install -g ftp-deploy

    - name: Add debugging information
      run: |
        echo "PATH: $PATH"
        which node
        which npm
        which ftp-deploy

    - name: Run FTP deploy
      run: ftp-deploy --username ${{ secrets.FTP_USERNAME }} --password ${{ secrets.FTP_PASSWORD }} --server ftp.dhirajghimire.com.np
